"""Narrow Python interface to the Partizan constrained-research engine."""

from ._native import analyze_subsystems, evaluate_position, find_locked_pawns
from .events import (
    EVENT_SCHEMA_VERSION,
    build_event_stream,
    canonical_event_bytes,
    validate_event_stream,
)
from .discovery import (
    POOL_SCHEMA_VERSION,
    POOL_SCHEMA_VERSION_V2,
    PROPOSAL_SCHEMA_VERSION,
    GENERATION_RECEIPT_SCHEMA_VERSION,
    RESULT_SCHEMA_VERSION,
    RUN_SCHEMA_VERSION,
    TARGET_SCHEMA_VERSION,
    VALUE_RULE,
    build_ranker_input,
    candidate_state_key_for,
    canonical_json_bytes,
    canonical_jsonl_bytes,
    fen_file_reflection_orbit_sha256,
    generation_receipt_id_for,
    partizan_pool_features_for_fen,
    validate_candidate_pool_manifest,
    validate_candidate_proposal,
    validate_discovery_bundle,
    validate_discovery_run,
    validate_generation_receipt,
    validate_target_spec,
    validate_verifier_result,
)

__all__ = [
    "EVENT_SCHEMA_VERSION",
    "POOL_SCHEMA_VERSION",
    "POOL_SCHEMA_VERSION_V2",
    "PROPOSAL_SCHEMA_VERSION",
    "GENERATION_RECEIPT_SCHEMA_VERSION",
    "RESULT_SCHEMA_VERSION",
    "RUN_SCHEMA_VERSION",
    "TARGET_SCHEMA_VERSION",
    "VALUE_RULE",
    "analyze_subsystems",
    "build_event_stream",
    "build_ranker_input",
    "candidate_state_key_for",
    "canonical_json_bytes",
    "canonical_jsonl_bytes",
    "canonical_event_bytes",
    "evaluate_position",
    "fen_file_reflection_orbit_sha256",
    "find_locked_pawns",
    "generation_receipt_id_for",
    "partizan_pool_features_for_fen",
    "validate_event_stream",
    "validate_candidate_pool_manifest",
    "validate_candidate_proposal",
    "validate_discovery_bundle",
    "validate_discovery_run",
    "validate_generation_receipt",
    "validate_target_spec",
    "validate_verifier_result",
]
__version__ = "0.1.0"
