"""Narrow Python interface to the Partizan constrained-research engine."""

from ._native import analyze_subsystems, evaluate_position, find_locked_pawns
from .events import (
    EVENT_SCHEMA_VERSION,
    build_event_stream,
    canonical_event_bytes,
    validate_event_stream,
)
from .discovery import (
    POOL_SCHEMA_VERSION,
    POOL_SCHEMA_VERSION_V2,
    PROPOSAL_SCHEMA_VERSION,
    GENERATION_RECEIPT_SCHEMA_VERSION,
    RESULT_SCHEMA_VERSION,
    RUN_SCHEMA_VERSION,
    TARGET_SCHEMA_VERSION,
    VALUE_RULE,
    build_ranker_input,
    candidate_state_key_for,
    canonical_json_bytes,
    canonical_jsonl_bytes,
    fen_file_reflection_orbit_sha256,
    generation_receipt_id_for,
    partizan_pool_features_for_fen,
    validate_candidate_pool_manifest,
    validate_candidate_proposal,
    validate_discovery_bundle,
    validate_discovery_run,
    validate_generation_receipt,
    validate_target_spec,
    validate_verifier_result,
)
from .fixed_value import (
    CANDIDATE_SCHEMA_VERSION as FIXED_VALUE_CANDIDATE_SCHEMA_VERSION,
    CERTIFICATE_SCHEMA_VERSION as FIXED_VALUE_CERTIFICATE_SCHEMA_VERSION,
    REPERTOIRE_SCHEMA_VERSION as FIXED_VALUE_REPERTOIRE_SCHEMA_VERSION,
    TARGET_SCHEMA_VERSION as FIXED_VALUE_TARGET_SCHEMA_VERSION,
    LiteralGameStats,
    ShortGameComparison,
    build_repertoire,
    canonicalize_literal_game,
    candidate_id_for as fixed_value_candidate_id_for,
    compare_repertoire_entries,
    compare_short_games,
    generate_candidates as generate_fixed_value_candidates,
    inspect_repertoire,
    literal_game_sha256,
    make_candidate as make_fixed_value_candidate,
    make_target as make_fixed_value_target,
    representation_sha256,
    target_id_for as fixed_value_target_id_for,
    validate_candidate as validate_fixed_value_candidate,
    validate_repertoire,
    validate_target as validate_fixed_value_target,
)

__all__ = [
    "EVENT_SCHEMA_VERSION",
    "POOL_SCHEMA_VERSION",
    "POOL_SCHEMA_VERSION_V2",
    "PROPOSAL_SCHEMA_VERSION",
    "GENERATION_RECEIPT_SCHEMA_VERSION",
    "RESULT_SCHEMA_VERSION",
    "RUN_SCHEMA_VERSION",
    "TARGET_SCHEMA_VERSION",
    "VALUE_RULE",
    "FIXED_VALUE_CANDIDATE_SCHEMA_VERSION",
    "FIXED_VALUE_CERTIFICATE_SCHEMA_VERSION",
    "FIXED_VALUE_REPERTOIRE_SCHEMA_VERSION",
    "FIXED_VALUE_TARGET_SCHEMA_VERSION",
    "LiteralGameStats",
    "ShortGameComparison",
    "analyze_subsystems",
    "build_event_stream",
    "build_ranker_input",
    "build_repertoire",
    "canonicalize_literal_game",
    "candidate_state_key_for",
    "canonical_json_bytes",
    "canonical_jsonl_bytes",
    "canonical_event_bytes",
    "evaluate_position",
    "fen_file_reflection_orbit_sha256",
    "find_locked_pawns",
    "fixed_value_candidate_id_for",
    "fixed_value_target_id_for",
    "generate_fixed_value_candidates",
    "generation_receipt_id_for",
    "inspect_repertoire",
    "literal_game_sha256",
    "make_fixed_value_candidate",
    "make_fixed_value_target",
    "partizan_pool_features_for_fen",
    "representation_sha256",
    "compare_repertoire_entries",
    "compare_short_games",
    "validate_event_stream",
    "validate_fixed_value_candidate",
    "validate_fixed_value_target",
    "validate_repertoire",
    "validate_candidate_pool_manifest",
    "validate_candidate_proposal",
    "validate_discovery_bundle",
    "validate_discovery_run",
    "validate_generation_receipt",
    "validate_target_spec",
    "validate_verifier_result",
]
__version__ = "0.1.0"
